/**
 * Frases y párrafos ORIGINALES para práctica. Cada entrada: [tema, texto].
 * SIN_TILDE: correctamente escritas sin ninguna tilde ni signo especial (mundos 1-5).
 * CON_TILDE: usan tildes, ü, ¿ ¡ y números (mundo 6 en adelante).
 * Un verificador (verificar-ortografia.mjs) revisa que SIN_TILDE no enseñe ortografía incorrecta.
 */
export const SIN_TILDE = [
  // animales
  ['animales', 'El perro corre en el parque.'], ['animales', 'La vaca come pasto en el campo.'], ['animales', 'Mi gato duerme sobre la cama.'],
  ['animales', 'El loro repite todo lo que oye.'], ['animales', 'La abeja lleva el polen a su casa.'], ['animales', 'Las hormigas trabajan juntas.'],
  ['animales', 'El oso come miel y frutas.'], ['animales', 'Un pez nada veloz en el agua.'], ['animales', 'La tortuga camina muy despacio.'],
  ['animales', 'El lobo aulla cuando sale la luna.'], ['animales', 'Mi conejo salta y come zanahoria.'], ['animales', 'La jirafa tiene el cuello largo.'],
  ['animales', 'La mariposa vuela entre las flores.'], ['animales', 'El caballo galopa por el campo verde.'], ['animales', 'La ardilla guarda nueces para el invierno.'],
  ['animales', 'Mi perro mueve la cola cuando me ve.'], ['animales', 'El gallo canta cuando sale el sol.'], ['animales', 'La rana salta de hoja en hoja.'],
  // escuela
  ['escuela', 'Hoy tenemos clase en el aula.'], ['escuela', 'Escribo mi tarea en el cuaderno.'], ['escuela', 'La profe lee un cuento a todos.'],
  ['escuela', 'Me gusta el recreo con mis amigos.'], ['escuela', 'Guardo mis libros en la mochila.'], ['escuela', 'Levanto la mano para pedir la palabra.'],
  ['escuela', 'Aprendo a escribir sin mirar el teclado.'], ['escuela', 'En la biblioteca hay mucho silencio.'], ['escuela', 'Mi maestra explica la clase con dibujos.'],
  ['escuela', 'Trabajamos en equipo para resolver el problema.'], ['escuela', 'Mi libro favorito es de aventuras.'],
  ['escuela', 'Pinto un paisaje con muchos colores.'], ['escuela', 'Mi cuaderno tiene una portada azul.'],
  // familia
  ['familia', 'Mi madre prepara arroz con pollo.'], ['familia', 'Mi padre me lleva a la escuela.'], ['familia', 'Mi abuela cuenta historias de su pueblo.'],
  ['familia', 'Mi hermano juega con la pelota conmigo.'], ['familia', 'Los domingos almorzamos todos juntos.'], ['familia', 'Mi abuelo cultiva flores en el patio.'],
  ['familia', 'En mi casa nos ayudamos entre todos.'], ['familia', 'Mi hermana lee un libro en su cama.'],
  ['familia', 'Mi prima pinta una flor roja.'],
  // naturaleza
  ['naturaleza', 'El sol sale por el este.'], ['naturaleza', 'La lluvia llena los lagos y las nubes.'], ['naturaleza', 'Los arbolitos dan sombra y aire limpio.'],
  ['naturaleza', 'El viento mueve las hojas del bosque.'], ['naturaleza', 'La luna brilla en el cielo de la noche.'],
  ['naturaleza', 'El mar es azul y muy profundo.'], ['naturaleza', 'Cuidemos el agua para el futuro.'], ['naturaleza', 'Las plantas necesitan sol y agua.'],
  ['naturaleza', 'En la selva viven miles de animales.'], ['naturaleza', 'Reciclar ayuda a cuidar el planeta.'],
  ['naturaleza', 'Una nube blanca pasa sobre el monte.'],
  // deportes
  ['deportes', 'Corro por el parque cada tarde.'], ['deportes', 'El portero ataja la pelota con las manos.'],
  ['deportes', 'Nadar es bueno para todo el cuerpo.'], ['deportes', 'Jugamos baloncesto en la cancha.'], ['deportes', 'El ciclista sube la montaña sin parar.'],
  ['deportes', 'Antes de jugar hay que calentar.'], ['deportes', 'Salto la cuerda con mis amigas.'], ['deportes', 'Mi equipo entrena todos los lunes.'],
  // tecnología
  ['tecnologia', 'Uso el computador para aprender.'], ['tecnologia', 'Escribo con los diez dedos sin mirar.'], ['tecnologia', 'La pantalla muestra el texto que escribo.'],
  ['tecnologia', 'Guardo mis archivos en una carpeta.'], ['tecnologia', 'Cuido mis datos y no comparto mi clave.'],
  ['tecnologia', 'Un robot puede ayudar en muchas tareas.'], ['tecnologia', 'Navego con permiso de un adulto.'],
  ['tecnologia', 'Mis dedos conocen cada tecla.'],
  // ciencia
  ['ciencia', 'La tierra gira alrededor del sol.'], ['ciencia', 'El agua hierve cuando hace mucho calor.'], ['ciencia', 'Las plantas hacen su comida con la luz.'],
  ['ciencia', 'La luna no tiene luz propia.'], ['ciencia', 'Los imanes atraen el hierro.'], ['ciencia', 'El sonido viaja por el aire.'],
  ['ciencia', 'El hielo se derrite con el calor.'],
  // colombia
  ['colombia', 'Colombia tiene costas en dos oceanos.'], ['colombia', 'La arepa es una comida muy querida.'], ['colombia', 'En Cali se baila salsa todo el año.'],
  ['colombia', 'Cartagena tiene murallas muy antiguas.'], ['colombia', 'La Amazonia es una selva enorme.'], ['colombia', 'Los Andes cruzan el territorio de norte a sur.'],
  ['colombia', 'En Pasto se celebra un gran carnaval.'],
  // comida
  ['comida', 'Desayuno pan con queso y jugo.'], ['comida', 'Me gusta el helado de fresa.'],
  ['comida', 'El arroz con huevo es mi plato favorito.'], ['comida', 'Tomo agua luego de jugar.'],
  ['comida', 'El jugo de mango es muy dulce.'], ['comida', 'La arepa con queso es deliciosa.'],
  // valores
  ['valores', 'Ser amable no cuesta nada.'], ['valores', 'Respeto a mis compañeros y a mi profe.'], ['valores', 'Pedir disculpas con respeto es ser valiente.'],
  ['valores', 'Compartir hace felices a todos.'], ['valores', 'Si me equivoco, lo intento otra vez.'],
  ['valores', 'La honestidad es un gran tesoro.'], ['valores', 'Cada error me ayuda a mejorar.'],
  // refranes
  ['refranes', 'A mal tiempo, buena cara.'], ['refranes', 'Quien madruga, Dios lo ayuda.'], ['refranes', 'Poco a poco se llega lejos.'],
  ['refranes', 'En boca cerrada no entran moscas.'],
  // trabalenguas
  ['trabalenguas', 'Tres tristes tigres tragaban trigo en tres tristes trastos.'],
  ['trabalenguas', 'Pepe Pecas pica papas con un pico, con un pico pica papas Pepe Pecas.'],
  // pangramas simples
  ['pangramas', 'Quiero zumo de piña y kiwi, dijo el ñu.'],
];


export const CON_TILDE = [
  ['signos', 'Necesito tres cosas: lápiz, cuaderno y borrador.'], ['signos', 'Hoy practico mucho; mañana practicaré más.'], ['signos', 'En mi mochila hay: libros, colores y una botella.'],
  ['signos', 'Me gusta el fútbol; mi hermana prefiere el baloncesto.'], ['signos', 'Recuerda: la precisión es primero.'], ['signos', 'Tengo dos mascotas: un gato y un perro.'],
  ['signos', 'Primero calentamos; después jugamos.'], ['signos', 'Mi lista de tareas: leer, escribir y dibujar.'], ['signos', 'Hay cuatro estaciones: verano, otoño, invierno y primavera.'],
  ['animales', 'El pingüino camina por el hielo.'], ['animales', 'El delfín es un animal muy inteligente.'], ['animales', 'Los pájaros cantan por la mañana.'],
  ['animales', 'El murciélago duerme de día y vuela de noche.'], ['animales', 'La ballena es el animal más grande del mar.'], ['animales', 'El león es el rey de la sabana.'],
  ['animales', 'El colibrí vuela muy rápido entre las flores.'], ['animales', 'La araña teje su tela con mucha paciencia.'], ['animales', '¡Qué grande es la jirafa!'],
  ['escuela', 'Hoy aprendí una lección nueva.'], ['escuela', 'Cada día practico un poco más.'], ['escuela', '¿Quién quiere pasar al tablero?'],
  ['escuela', 'Mi maestra me felicitó por mi esfuerzo.'], ['escuela', 'En el salón hay veinte pupitres.'], ['escuela', 'La tarea de matemáticas es muy fácil.'],
  ['escuela', '¿Cómo se escribe esta palabra?'], ['escuela', 'Mañana tenemos examen de ciencias.'], ['escuela', 'Leí un libro sobre el espacio.'],
  ['familia', 'Mi mamá prepara arroz con pollo.'], ['familia', 'Mi papá me lleva a la escuela.'], ['familia', 'Mi tía vive cerca de la playa.'],
  ['familia', 'Mi familia es lo más importante.'], ['familia', 'Mañana es el cumpleaños de mi prima.'], ['familia', '¡Feliz cumpleaños, papá!'],
  ['familia', 'Mi abuelo me enseñó a jugar ajedrez.'], ['familia', '¿Quieres jugar conmigo, hermano?'], ['familia', 'Mi mamá me dio un abrazo muy fuerte.'],
  ['naturaleza', 'El arcoíris aparece después de la lluvia.'], ['naturaleza', '¡Qué bonito está el cielo hoy!'], ['naturaleza', 'Las montañas son altas y frías.'],
  ['naturaleza', 'El río baja desde la montaña hasta el mar.'], ['naturaleza', 'Los árboles dan sombra y aire limpio.'], ['naturaleza', 'La flor abre sus pétalos con el sol.'],
  ['naturaleza', 'Después de la tormenta sale el sol.'], ['naturaleza', '¿Sabías que las plantas también respiran?'],
  ['deportes', 'El fútbol es el deporte más popular de Colombia.'], ['deportes', '¡Gol! Todos gritamos de alegría.'], ['deportes', 'Mi equipo ganó el partido con un gol de último minuto.'],
  ['deportes', '¿Quién ganó la carrera de ciclismo?'], ['deportes', 'El básquetbol se juega con las manos.'], ['deportes', 'Entrenar cada día me hace más fuerte.'],
  ['tecnologia', 'La precisión es más importante que la prisa.'], ['tecnologia', '¿Sabías que la tecla F tiene un puntito?'], ['tecnologia', 'Mi computador tiene una pantalla muy nítida.'],
  ['tecnologia', 'La tecnología nos ayuda a aprender más rápido.'], ['tecnologia', 'Escribir bien me permite trabajar mejor.'], ['tecnologia', '¿Cuál es tu juego favorito?'],
  ['ciencia', 'El corazón bombea sangre a todo el cuerpo.'], ['ciencia', 'Los científicos hacen preguntas y buscan respuestas.'], ['ciencia', 'Júpiter es el planeta más grande del sistema solar.'],
  ['ciencia', '¿Por qué el cielo es azul?'], ['ciencia', 'El agua hierve a cien grados.'], ['ciencia', 'Los imanes tienen dos polos: norte y sur.'],
  ['colombia', 'El río Magdalena cruza gran parte del país.'], ['colombia', 'El café colombiano es famoso en el mundo.'], ['colombia', 'Bogotá es la capital de Colombia.'],
  ['colombia', 'El cóndor es un ave que vuela sobre los Andes.'], ['colombia', '¡Qué rica está la bandeja paisa!'], ['colombia', 'Medellín es conocida como la ciudad de la eterna primavera.'],
  ['colombia', 'En el Caribe colombiano se baila cumbia.'], ['colombia', '¿Conoces el Valle de Cocora?'],
  ['comida', 'La arepa con queso está deliciosa.'], ['comida', 'El jugo de maracuyá es mi favorito.'], ['comida', 'Mi mamá hace un pastel de limón riquísimo.'],
  ['comida', '¿Quieres un plátano o una manzana?'], ['comida', 'Tomé un vaso de leche con galletas.'],
  ['valores', '¡Tú puedes lograrlo!'], ['valores', 'Pedir perdón también es ser valiente.'], ['valores', 'Con paciencia y práctica todo se logra.'],
  ['valores', '¡Gracias por ayudarme!'], ['valores', 'Respeto a mis compañeros y a mi profe.'], ['valores', '¿Cómo puedo ayudarte hoy?'],
  ['refranes', 'Más vale tarde que nunca.'], ['refranes', 'Más sabe el diablo por viejo que por diablo.'], ['refranes', 'Camarón que se duerme se lo lleva la corriente.'],
  ['refranes', 'No dejes para mañana lo que puedes hacer hoy.'], ['refranes', 'Dime con quién andas y te diré quién eres.'],
  ['trabalenguas', 'Pablito clavó un clavito en la calva de un calvito.'], ['trabalenguas', 'El cielo está enladrillado, ¿quién lo desenladrillará?'],
  ['trabalenguas', 'Erre con erre cigarro, erre con erre barril, rápido ruedan los carros cargados de azúcar al ferrocarril.'],
  ['pangramas', 'El veloz murciélago hindú comía feliz cardillo y kiwi.'], ['pangramas', 'Quiero zumo de piña y kiwi, dijo el ñandú.'], ['pangramas', 'La cigüeña tocaba el saxofón detrás del palenque de paja.'],
  ['numeros', 'Tengo 8 años y mi casa es la 25.'], ['numeros', 'El partido empieza a las 3:30 de la tarde.'], ['numeros', 'Compré 4 lápices por $2.500.'],
  ['numeros', 'Mi correo es sofia@colegio.edu.co.'], ['numeros', 'El 100% de mis tareas están listas.'], ['numeros', 'Hoy es 15/03/2026.'],
  ['numeros', 'Mi número de lista es el 17.'], ['numeros', '2 + 3 = 5 y 10 - 4 = 6.'], ['numeros', 'La clave tiene 6 números y 1 símbolo (#).'],
  ['numeros', 'Somos 28 estudiantes en el salón 4-B.'], ['numeros', 'El bus sale a las 6:45 y llega a las 7:15.'], ['numeros', 'Mi teléfono termina en 0-7-3.'],
  ['numeros', 'La nota fue 4,5 y la meta era 4,0.'], ['numeros', 'Escribe @ con la tecla AltGr y la Q.'], ['numeros', 'Pagué $12.000 y me devolvieron $3.500.'],
];

export const PARRAFOS = [
  ['ciencia', 'El sistema solar tiene ocho planetas que giran alrededor del sol. La tierra es el tercero y es el único donde se conoce la vida. Cada planeta tarda un tiempo distinto en dar su vuelta completa.'],
  ['ciencia', 'Las plantas son seres vivos que fabrican su alimento con la luz del sol. Absorben agua por las raíces y aire por las hojas. Gracias a ellas respiramos mejor.'],
  ['ciencia', 'El agua cambia de estado según la temperatura. Con mucho frío se vuelve hielo, con calor se convierte en vapor y en las nubes vuelve a formar gotas. A este recorrido se le llama ciclo del agua.'],
  ['ciencia', 'El cuerpo humano tiene huesos, músculos y órganos que trabajan juntos. El corazón late sin descanso y los pulmones llevan el aire a la sangre. Dormir bien y comer sano ayudan a cuidarlo.'],
  ['ciencia', 'Un volcán es una montaña por donde sale roca derretida desde el interior de la tierra. Cuando está dormido no expulsa lava, pero algunos pueden despertar. Los científicos los vigilan para proteger a las personas.'],
  ['ciencia', 'La luz del sol tarda unos ocho minutos en llegar a la tierra. Viaja muy rápido, mucho más que cualquier carro o avión. Gracias a esa luz hay día, plantas y colores.'],
  ['animales', 'Las abejas viven en colmenas y cada una tiene un trabajo. Unas buscan flores, otras cuidan a las crías y otras guardan la miel. Sin ellas muchas plantas no podrían dar frutos.'],
  ['animales', 'Los delfines son mamíferos que viven en el mar. Se comunican con silbidos y saltan sobre las olas. Viajan en grupos y se cuidan unos a otros.'],
  ['animales', 'El colibrí es el ave más pequeña y puede quedarse quieta en el aire moviendo las alas muy rápido. Se alimenta del néctar de las flores. En Colombia viven más de cien especies distintas.'],
  ['animales', 'Las tortugas marinas regresan a la misma playa donde nacieron para poner sus huevos. Los pequeños salen de noche y corren hacia el mar. Cuidar las playas les da más oportunidades de sobrevivir.'],
  ['animales', 'El oso de anteojos vive en las montañas de los Andes. Tiene manchas claras alrededor de los ojos y come frutas, hojas y raíces. Es un animal tímido que prefiere evitar a las personas.'],
  ['colombia', 'Colombia es un país lleno de colores y de música. Tiene montañas, selvas, desiertos y playas en dos mares. Cada región tiene sus comidas, sus bailes y sus costumbres.'],
  ['colombia', 'El río Amazonas nace lejos, pero una parte de la selva amazónica pertenece a Colombia. Allí viven delfines rosados, monos y miles de especies de plantas. Cuidar la selva es cuidar el aire de todo el planeta.'],
  ['colombia', 'El café crece en las montañas del Eje Cafetero. Las familias recogen los granos rojos a mano y los secan al sol. Después de un largo proceso, llegan a nuestras tazas.'],
  ['colombia', 'El Caribe colombiano tiene playas de arena blanca, islas y pueblos con mucha historia. Allí se escucha cumbia y vallenato. El mar tiene un color azul tan claro que parece pintado.'],
  ['colombia', 'En el Pacífico colombiano llueve casi todo el año y la selva es muy verde. Entre junio y noviembre llegan las ballenas jorobadas a tener a sus crías. Es un espectáculo que visitantes de todo el mundo vienen a ver.'],
  ['naturaleza', 'Un bosque es mucho más que árboles. Allí viven insectos, aves, hongos y animales que dependen unos de otros. Si cuidamos cada parte, el bosque sigue vivo y sano.'],
  ['naturaleza', 'Reciclar es separar los residuos para darles una nueva vida. El papel, el vidrio y el plástico pueden transformarse en objetos nuevos. Cada persona puede ayudar con pequeños gestos todos los días.'],
  ['naturaleza', 'Los ríos nacen en las montañas y bajan hasta el mar. En su camino dan agua a las personas, a los cultivos y a los animales. Mantenerlos limpios es una tarea de todos.'],
  ['tecnologia', 'Aprender a teclear sin mirar el teclado es una habilidad para toda la vida. Al principio parece lento, pero con práctica diaria los dedos aprenden dónde está cada tecla. La clave es ir despacio y no cometer errores.'],
  ['tecnologia', 'Internet conecta computadores de todo el mundo. Nos permite buscar información, escribir mensajes y aprender cosas nuevas. Para usarlo bien debemos cuidar nuestros datos y pedir ayuda cuando algo no nos parezca seguro.'],
  ['tecnologia', 'Una buena postura evita el cansancio. La espalda va recta, los pies apoyados en el piso y los codos doblados en ángulo recto. La pantalla debe quedar a la altura de los ojos.'],
  ['tecnologia', 'Un robot es una máquina que sigue instrucciones. Algunos limpian, otros arman piezas y otros exploran lugares peligrosos. Alguien tuvo que escribir con mucho cuidado las órdenes que los guían.'],
  ['cuento', 'Había una vez un zorro curioso que quería aprender a escribir. Todos los días practicaba un poco con sus patas sobre el teclado. Al cabo de un mes ya escribía sin mirar, y su primer mensaje fue una carta de agradecimiento para su maestra.'],
  ['cuento', 'En un pueblo junto al río vivía una niña que amaba los libros. Cada tarde se sentaba bajo un árbol a leer historias de viajeros. Un día decidió escribir la suya, y todos los vecinos quisieron leerla.'],
  ['cuento', 'Un pequeño robot se perdió en el bosque y no sabía cómo volver. Un búho sabio le enseñó a seguir las estrellas. Desde esa noche, el robot nunca dejó de mirar el cielo con gratitud.'],
  ['cuento', 'Dos amigos construyeron una nave con cajas de cartón. Aunque no volaba, con su imaginación viajaron a la luna y a los planetas. Al regresar a casa tenían miles de historias para contar.'],
  ['cuento', 'Una tortuga y una liebre se encontraron en el camino. La liebre se burló de lo lenta que era la tortuga. Ella siguió caminando sin parar, y al final llegó primero porque nunca se rindió.'],
  ['valores', 'La amabilidad es como una semilla: cuando la plantas, crece y da frutos. Un saludo, una sonrisa o una ayuda pequeña pueden cambiarle el día a alguien. Practicarla también nos hace sentir bien.'],
  ['valores', 'Equivocarse es parte de aprender. Cada error nos muestra qué debemos mejorar y nos da otra oportunidad de intentarlo. Lo importante es no rendirse y seguir practicando con paciencia.'],
  ['valores', 'Trabajar en equipo significa escuchar, compartir ideas y respetar los turnos. Cuando cada persona aporta lo que mejor sabe hacer, el resultado es más grande que la suma de las partes.'],
  ['deportes', 'Para ser un buen deportista hay que entrenar con constancia. Calentar, hidratarse y descansar son tan importantes como jugar. Y lo más valioso es disfrutar y respetar a los demás jugadores.'],
  ['deportes', 'El ciclismo es muy querido en Colombia. Las carreteras de montaña ofrecen grandes retos a los ciclistas. Cada vez que uno de ellos gana una etapa, todo el país celebra.'],
  ['comida', 'La arepa se prepara con maíz y se puede rellenar con queso, huevo o carne. En cada región tiene un sabor y una forma diferente. Es perfecta para el desayuno y también para la cena.'],
  ['comida', 'Comer variado ayuda al cuerpo a crecer fuerte. Las frutas y verduras aportan vitaminas, los cereales dan energía y las proteínas construyen los músculos. Tomar agua durante el día también es fundamental.'],
  ['historia', 'Hace muchos años, los pueblos indígenas ya vivían en el territorio que hoy es Colombia. Trabajaron el oro, cultivaron maíz y construyeron caminos. Su legado sigue vivo en nuestras palabras, comidas y tradiciones.'],
  ['historia', 'La imprenta fue una invención que permitió copiar libros con rapidez. Antes de ella, cada libro se escribía a mano y era muy costoso. Gracias a este invento, las ideas viajaron por todo el mundo.'],
  ['historia', 'La máquina de escribir apareció hace más de ciento cincuenta años. Sus teclas estaban en el mismo orden que usamos hoy en el teclado del computador. Por eso las letras Q, W, E, R, T, Y se encuentran juntas.'],
  ['espacio', 'La luna es el único satélite natural de la tierra. Su superficie está llena de cráteres y no tiene aire. En el año mil novecientos sesenta y nueve, los primeros astronautas caminaron sobre ella.'],
  ['espacio', 'Las estrellas son enormes bolas de gas que brillan con luz propia. El sol es la más cercana a nosotros. De noche vemos otras mucho más lejanas que parecen puntos pequeños.'],
  ['numeros', 'Mi colegio abre a las 6:30 de la mañana y cierra a las 3:00 de la tarde. Tenemos 7 clases por día y 1 recreo de 30 minutos. Mi salón es el 5-B y somos 28 estudiantes.'],
  ['numeros', 'En la tienda compré 3 cuadernos a $4.500 cada uno y 2 lápices a $1.200. En total pagué $15.900. Me devolvieron $4.100 porque entregué un billete de $20.000.'],
  ['numeros', 'Para crear una clave segura usa por lo menos 8 caracteres: letras mayúsculas, minúsculas, 2 números y un símbolo como #, @ o %. Nunca la compartas con nadie, ¡ni siquiera con tus amigos!'],
  ['dialogo', '—¡Buenos días, profe! —dijo Sofía. —Buenos días, ¿cómo amaneciste? —respondió la maestra. —Muy bien, hoy quiero aprender a escribir sin mirar. —¡Excelente idea! Empecemos con la fila base.'],
  ['dialogo', '—¿Qué vas a hacer en vacaciones? —preguntó Mateo. —Voy a visitar a mis abuelos en el campo —contestó Valentina—. ¡Montaré a caballo y recogeré frutas! —¡Qué divertido! —exclamó Mateo.'],
];
